// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: auth.message.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JwtIssuanceStatus int32

const (
	JwtIssuanceStatus_UNDEFINED_ISSUANCE JwtIssuanceStatus = 0 //발행 상태가 정의되지 않음
	JwtIssuanceStatus_ACCESS_ISSUANCE    JwtIssuanceStatus = 1 // 엑세스만
	JwtIssuanceStatus_REFRESH_ISSUANCE   JwtIssuanceStatus = 2 //리프레쉬만
	JwtIssuanceStatus_BOTH_ISSUANCE      JwtIssuanceStatus = 3 //모두발행
)

// Enum value maps for JwtIssuanceStatus.
var (
	JwtIssuanceStatus_name = map[int32]string{
		0: "UNDEFINED_ISSUANCE",
		1: "ACCESS_ISSUANCE",
		2: "REFRESH_ISSUANCE",
		3: "BOTH_ISSUANCE",
	}
	JwtIssuanceStatus_value = map[string]int32{
		"UNDEFINED_ISSUANCE": 0,
		"ACCESS_ISSUANCE":    1,
		"REFRESH_ISSUANCE":   2,
		"BOTH_ISSUANCE":      3,
	}
)

func (x JwtIssuanceStatus) Enum() *JwtIssuanceStatus {
	p := new(JwtIssuanceStatus)
	*p = x
	return p
}

func (x JwtIssuanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JwtIssuanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_message_proto_enumTypes[0].Descriptor()
}

func (JwtIssuanceStatus) Type() protoreflect.EnumType {
	return &file_auth_message_proto_enumTypes[0]
}

func (x JwtIssuanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JwtIssuanceStatus.Descriptor instead.
func (JwtIssuanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_auth_message_proto_rawDescGZIP(), []int{0}
}

type JwtSecure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JwtIssuanceStatus JwtIssuanceStatus `protobuf:"varint,2,opt,name=jwt_issuance_status,json=jwtIssuanceStatus,proto3,enum=authpb.JwtIssuanceStatus" json:"jwt_issuance_status,omitempty"`
}

func (x *JwtSecure) Reset() {
	*x = JwtSecure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtSecure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtSecure) ProtoMessage() {}

func (x *JwtSecure) ProtoReflect() protoreflect.Message {
	mi := &file_auth_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtSecure.ProtoReflect.Descriptor instead.
func (*JwtSecure) Descriptor() ([]byte, []int) {
	return file_auth_message_proto_rawDescGZIP(), []int{0}
}

func (x *JwtSecure) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JwtSecure) GetJwtIssuanceStatus() JwtIssuanceStatus {
	if x != nil {
		return x.JwtIssuanceStatus
	}
	return JwtIssuanceStatus_UNDEFINED_ISSUANCE
}

type DeJwtSecure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorStatus  bool   `protobuf:"varint,3,opt,name=error_status,json=errorStatus,proto3" json:"error_status,omitempty"`
}

func (x *DeJwtSecure) Reset() {
	*x = DeJwtSecure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeJwtSecure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeJwtSecure) ProtoMessage() {}

func (x *DeJwtSecure) ProtoReflect() protoreflect.Message {
	mi := &file_auth_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeJwtSecure.ProtoReflect.Descriptor instead.
func (*DeJwtSecure) Descriptor() ([]byte, []int) {
	return file_auth_message_proto_rawDescGZIP(), []int{1}
}

func (x *DeJwtSecure) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeJwtSecure) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeJwtSecure) GetErrorStatus() bool {
	if x != nil {
		return x.ErrorStatus
	}
	return false
}

type JwtToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorization        string `protobuf:"bytes,1,opt,name=authorization,proto3" json:"authorization,omitempty"`
	RefreshAuthorization string `protobuf:"bytes,2,opt,name=refresh_authorization,json=refreshAuthorization,proto3" json:"refresh_authorization,omitempty"`
	ErrorMessage         string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorStatus          bool   `protobuf:"varint,4,opt,name=error_status,json=errorStatus,proto3" json:"error_status,omitempty"`
}

func (x *JwtToken) Reset() {
	*x = JwtToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JwtToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JwtToken) ProtoMessage() {}

func (x *JwtToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JwtToken.ProtoReflect.Descriptor instead.
func (*JwtToken) Descriptor() ([]byte, []int) {
	return file_auth_message_proto_rawDescGZIP(), []int{2}
}

func (x *JwtToken) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *JwtToken) GetRefreshAuthorization() string {
	if x != nil {
		return x.RefreshAuthorization
	}
	return ""
}

func (x *JwtToken) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JwtToken) GetErrorStatus() bool {
	if x != nil {
		return x.ErrorStatus
	}
	return false
}

var File_auth_message_proto protoreflect.FileDescriptor

var file_auth_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x75, 0x74, 0x68, 0x70, 0x62, 0x22, 0x66, 0x0a, 0x09,
	0x4a, 0x77, 0x74, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x49, 0x0a, 0x13, 0x6a, 0x77, 0x74,
	0x5f, 0x69, 0x73, 0x73, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x70, 0x62, 0x2e,
	0x4a, 0x77, 0x74, 0x49, 0x73, 0x73, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x11, 0x6a, 0x77, 0x74, 0x49, 0x73, 0x73, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x65, 0x0a, 0x0b, 0x44, 0x65, 0x4a, 0x77, 0x74, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x08,
	0x4a, 0x77, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x33,
	0x0a, 0x15, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x72,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x69, 0x0a, 0x11, 0x4a,
	0x77, 0x74, 0x49, 0x73, 0x73, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x12, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x49, 0x53,
	0x53, 0x55, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x41, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x5f, 0x49, 0x53, 0x53, 0x55, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a,
	0x10, 0x52, 0x45, 0x46, 0x52, 0x45, 0x53, 0x48, 0x5f, 0x49, 0x53, 0x53, 0x55, 0x41, 0x4e, 0x43,
	0x45, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x4f, 0x54, 0x48, 0x5f, 0x49, 0x53, 0x53, 0x55,
	0x41, 0x4e, 0x43, 0x45, 0x10, 0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth_message_proto_rawDescOnce sync.Once
	file_auth_message_proto_rawDescData = file_auth_message_proto_rawDesc
)

func file_auth_message_proto_rawDescGZIP() []byte {
	file_auth_message_proto_rawDescOnce.Do(func() {
		file_auth_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_message_proto_rawDescData)
	})
	return file_auth_message_proto_rawDescData
}

var file_auth_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_message_proto_goTypes = []interface{}{
	(JwtIssuanceStatus)(0), // 0: authpb.JwtIssuanceStatus
	(*JwtSecure)(nil),      // 1: authpb.JwtSecure
	(*DeJwtSecure)(nil),    // 2: authpb.DeJwtSecure
	(*JwtToken)(nil),       // 3: authpb.JwtToken
}
var file_auth_message_proto_depIdxs = []int32{
	0, // 0: authpb.JwtSecure.jwt_issuance_status:type_name -> authpb.JwtIssuanceStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_message_proto_init() }
func file_auth_message_proto_init() {
	if File_auth_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtSecure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeJwtSecure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JwtToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_message_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_message_proto_goTypes,
		DependencyIndexes: file_auth_message_proto_depIdxs,
		EnumInfos:         file_auth_message_proto_enumTypes,
		MessageInfos:      file_auth_message_proto_msgTypes,
	}.Build()
	File_auth_message_proto = out.File
	file_auth_message_proto_rawDesc = nil
	file_auth_message_proto_goTypes = nil
	file_auth_message_proto_depIdxs = nil
}
