// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthGrpcServiceClient is the client API for AuthGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGrpcServiceClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LocalT2Issuer(ctx context.Context, in *JwtSecure, opts ...grpc.CallOption) (*JwtToken, error)
	LocalT1Issuer(ctx context.Context, in *JwtSecure, opts ...grpc.CallOption) (*JwtToken, error)
	VerifyJwtAccess(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeJwtSecure, error)
	VerifyJwtRefresh(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeJwtSecure, error)
}

type authGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGrpcServiceClient(cc grpc.ClientConnInterface) AuthGrpcServiceClient {
	return &authGrpcServiceClient{cc}
}

func (c *authGrpcServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/authpb.AuthGrpcService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) LocalT2Issuer(ctx context.Context, in *JwtSecure, opts ...grpc.CallOption) (*JwtToken, error) {
	out := new(JwtToken)
	err := c.cc.Invoke(ctx, "/authpb.AuthGrpcService/LocalT2Issuer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) LocalT1Issuer(ctx context.Context, in *JwtSecure, opts ...grpc.CallOption) (*JwtToken, error) {
	out := new(JwtToken)
	err := c.cc.Invoke(ctx, "/authpb.AuthGrpcService/LocalT1Issuer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) VerifyJwtAccess(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeJwtSecure, error) {
	out := new(DeJwtSecure)
	err := c.cc.Invoke(ctx, "/authpb.AuthGrpcService/VerifyJwtAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authGrpcServiceClient) VerifyJwtRefresh(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeJwtSecure, error) {
	out := new(DeJwtSecure)
	err := c.cc.Invoke(ctx, "/authpb.AuthGrpcService/VerifyJwtRefresh", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthGrpcServiceServer is the server API for AuthGrpcService service.
// All implementations must embed UnimplementedAuthGrpcServiceServer
// for forward compatibility
type AuthGrpcServiceServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	LocalT2Issuer(context.Context, *JwtSecure) (*JwtToken, error)
	LocalT1Issuer(context.Context, *JwtSecure) (*JwtToken, error)
	VerifyJwtAccess(context.Context, *emptypb.Empty) (*DeJwtSecure, error)
	VerifyJwtRefresh(context.Context, *emptypb.Empty) (*DeJwtSecure, error)
	mustEmbedUnimplementedAuthGrpcServiceServer()
}

// UnimplementedAuthGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthGrpcServiceServer struct {
}

func (UnimplementedAuthGrpcServiceServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAuthGrpcServiceServer) LocalT2Issuer(context.Context, *JwtSecure) (*JwtToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalT2Issuer not implemented")
}
func (UnimplementedAuthGrpcServiceServer) LocalT1Issuer(context.Context, *JwtSecure) (*JwtToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocalT1Issuer not implemented")
}
func (UnimplementedAuthGrpcServiceServer) VerifyJwtAccess(context.Context, *emptypb.Empty) (*DeJwtSecure, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyJwtAccess not implemented")
}
func (UnimplementedAuthGrpcServiceServer) VerifyJwtRefresh(context.Context, *emptypb.Empty) (*DeJwtSecure, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyJwtRefresh not implemented")
}
func (UnimplementedAuthGrpcServiceServer) mustEmbedUnimplementedAuthGrpcServiceServer() {}

// UnsafeAuthGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGrpcServiceServer will
// result in compilation errors.
type UnsafeAuthGrpcServiceServer interface {
	mustEmbedUnimplementedAuthGrpcServiceServer()
}

func RegisterAuthGrpcServiceServer(s grpc.ServiceRegistrar, srv AuthGrpcServiceServer) {
	s.RegisterService(&AuthGrpcService_ServiceDesc, srv)
}

func _AuthGrpcService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthGrpcService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_LocalT2Issuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtSecure)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).LocalT2Issuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthGrpcService/LocalT2Issuer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).LocalT2Issuer(ctx, req.(*JwtSecure))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_LocalT1Issuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JwtSecure)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).LocalT1Issuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthGrpcService/LocalT1Issuer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).LocalT1Issuer(ctx, req.(*JwtSecure))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_VerifyJwtAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).VerifyJwtAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthGrpcService/VerifyJwtAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).VerifyJwtAccess(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthGrpcService_VerifyJwtRefresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServiceServer).VerifyJwtRefresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.AuthGrpcService/VerifyJwtRefresh",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServiceServer).VerifyJwtRefresh(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthGrpcService_ServiceDesc is the grpc.ServiceDesc for AuthGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.AuthGrpcService",
	HandlerType: (*AuthGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AuthGrpcService_Ping_Handler,
		},
		{
			MethodName: "LocalT2Issuer",
			Handler:    _AuthGrpcService_LocalT2Issuer_Handler,
		},
		{
			MethodName: "LocalT1Issuer",
			Handler:    _AuthGrpcService_LocalT1Issuer_Handler,
		},
		{
			MethodName: "VerifyJwtAccess",
			Handler:    _AuthGrpcService_VerifyJwtAccess_Handler,
		},
		{
			MethodName: "VerifyJwtRefresh",
			Handler:    _AuthGrpcService_VerifyJwtRefresh_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.service.proto",
}
